import { ScrollViewStyleReset } from 'expo-router/html';
import type { PropsWithChildren } from 'react';

/**
 * The HTML shell for the static web / PWA build. Only rendered on web, at
 * export time (Node), so it can't use browser APIs or app state.
 */
export default function Root({ children }: PropsWithChildren) {
  const production = process.env.NODE_ENV === 'production';
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
        <meta
          name="description"
          content="Learn the physiology behind your calm — breath, touch and movement — well enough that you need the app less."
        />

        {/* Installable app */}
        <link rel="manifest" href="/manifest.webmanifest" />
        <meta name="theme-color" content="#ffffff" />
        <link rel="apple-touch-icon" href="/icons/apple-touch-icon.png" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-title" content="Exhale" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />

        <ScrollViewStyleReset />
        <style dangerouslySetInnerHTML={{ __html: baseStyles }} />

        {/* Offline support. The service worker is generated by scripts/generate-sw.mjs after `expo export`. */}
        {production ? <script dangerouslySetInnerHTML={{ __html: registerServiceWorker }} /> : null}
      </head>
      <body>{children}</body>
    </html>
  );
}

const baseStyles = `
html, body { background-color: #ffffff; overscroll-behavior: none; }
body { -webkit-tap-highlight-color: transparent; }
`;

const registerServiceWorker = `
if ('serviceWorker' in navigator) {
  window.addEventListener('load', function () {
    navigator.serviceWorker.register('/sw.js').catch(function () {});
  });
}
`;
